"""
OrderDB / OrderItemDB: the checkout record — what was bought, at what
price (snapshotted at purchase time, so later price changes never alter
a past receipt), and its payment status.

Deliberately kept separate from DeliveryRecordDB: an Order is "what was
purchased and whether it was paid for"; a Delivery is "the physical
fulfillment/shipment of it". On successful payment, checkout.py creates
ONE DeliveryRecordDB row from this order (see routes/checkout.py) and
links back to it via delivery_id — from that point on, the existing
dispatcher/agent pipeline (unchanged) handles getting it to the
customer's door, and it shows up in the customer's existing "My Orders"
tracking view exactly like any other delivery.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import Column, String, DateTime, Float, Integer, Enum as SqlEnum
from pydantic import BaseModel
from typing import Optional, List

from app.db.session import Base


class OrderStatus(str, enum.Enum):
    pending_payment = "pending_payment"
    paid = "paid"
    payment_failed = "payment_failed"


class OrderDB(Base):
    __tablename__ = "orders"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    customer_id = Column(String, index=True, nullable=False)
    org_id = Column(String, index=True, nullable=False)
    status = Column(SqlEnum(OrderStatus), nullable=False, default=OrderStatus.pending_payment)

    address_line = Column(String, nullable=False)
    city = Column(String, nullable=True)
    phone = Column(String, nullable=False)

    subtotal = Column(Float, nullable=False)  # pure product subtotal — unchanged meaning, never includes fee/tax/discount

    # Pricing breakdown, computed once at checkout() and never
    # recalculated afterwards (so a later coupon/fee/tax config change
    # never alters a receipt that already exists). `total` is the actual
    # amount charged — subtotal - discount_amount + delivery_fee + tax_amount.
    coupon_code = Column(String, nullable=True)
    discount_amount = Column(Float, nullable=False, default=0.0)
    delivery_fee = Column(Float, nullable=False, default=0.0)
    tax_amount = Column(Float, nullable=False, default=0.0)
    total = Column(Float, nullable=False, default=0.0)

    # Real Razorpay identifiers — set once a payment attempt/order is
    # actually created with Razorpay. See services/payment.py.
    razorpay_order_id = Column(String, nullable=True)
    razorpay_payment_id = Column(String, nullable=True)

    # "online" (paid upfront via Razorpay, or the test-mode stand-in) or
    # "cod" (cash on delivery — the customer pays the agent in person
    # when the order arrives, nothing is charged at checkout time at
    # all). Set once at checkout and never changed afterwards.
    payment_method = Column(String, nullable=False, default="online")

    # True only when no Razorpay keys are configured and this order went
    # through the clearly-labeled fallback path instead of a real
    # gateway — see services/payment.py's module docstring for why this
    # exists and how it's surfaced to the customer.
    is_test_mode_payment = Column(Integer, nullable=False, default=0)  # 0/1 as SQLite has no native bool constraint issues here

    # Refund tracking — set by services/refund.py when a paid order is
    # cancelled (customer self-serve or dispatcher/admin side). None
    # means "never refunded / nothing to refund". See services/refund.py
    # for what "refunded" means for a test-mode order vs a real one.
    refund_status = Column(String, nullable=True)  # None | "refunded" | "failed"
    razorpay_refund_id = Column(String, nullable=True)
    refunded_at = Column(DateTime, nullable=True)

    # Set once stock has been credited back for a cancelled order — see
    # services/inventory.py.restock_order_if_needed(). Idempotency guard,
    # same 0/1 pattern as is_test_mode_payment.
    stock_restored = Column(Integer, nullable=False, default=0)

    # Delivery time-slot the customer picked at checkout (see
    # routes/slots.py) — None means "ASAP / no preference", same as
    # skipping a coupon. Copied onto the DeliveryRecordDB created in
    # verify_payment() so a dispatcher/agent can see it without
    # cross-referencing the order.
    slot_start = Column(DateTime, nullable=True)
    slot_end = Column(DateTime, nullable=True)

    delivery_id = Column(String, nullable=True)  # set once payment is verified and a Delivery is created
    created_at = Column(DateTime, nullable=False)

    # Set only when this order was generated by the recurring-orders
    # scheduler (services/subscription_scheduler.py) rather than a normal
    # cart checkout — None for every ordinary order. Lets the customer's
    # Subscriptions view find "the order this cycle produced" and lets
    # routes/subscriptions.py's pay endpoint confirm an order it's about
    # to charge really did come from that subscription.
    subscription_id = Column(String, nullable=True, index=True)


class OrderItemDB(Base):
    __tablename__ = "order_items"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    order_id = Column(String, index=True, nullable=False)
    product_id = Column(String, nullable=False)
    product_name = Column(String, nullable=False)   # snapshotted at purchase time
    unit_price = Column(Float, nullable=False)       # snapshotted at purchase time
    quantity = Column(Integer, nullable=False)


class CheckoutRequest(BaseModel):
    address_line: str
    city: Optional[str] = None
    phone: str
    coupon_code: Optional[str] = None
    slot_start: Optional[datetime] = None  # must exactly match one of GET /stores/{org_id}/delivery-slots's returned options
    payment_method: str = "online"  # "online" or "cod" — validated in routes/checkout.py


class OrderItemOut(BaseModel):
    product_id: str
    product_name: str
    unit_price: float
    quantity: int

    class Config:
        from_attributes = True


class OrderOut(BaseModel):
    id: str
    status: OrderStatus
    address_line: str
    city: Optional[str] = None
    phone: str
    subtotal: float
    coupon_code: Optional[str] = None
    discount_amount: float = 0.0
    delivery_fee: float = 0.0
    tax_amount: float = 0.0
    total: float = 0.0
    is_test_mode_payment: bool
    payment_method: str = "online"
    refund_status: Optional[str] = None
    refunded_at: Optional[datetime] = None
    slot_start: Optional[datetime] = None
    slot_end: Optional[datetime] = None
    delivery_id: Optional[str] = None
    subscription_id: Optional[str] = None
    created_at: datetime
    items: List[OrderItemOut] = []

    class Config:
        from_attributes = True


class CheckoutResponse(BaseModel):
    """
    What the frontend needs to either launch Razorpay's real Checkout.js
    widget (when a real gateway is configured) or show the clearly-
    labeled test-mode confirmation flow (when it isn't). Also carries
    the full price breakdown so the frontend can show a proper receipt
    before/while payment happens, without a second round trip.
    """
    order_id: str
    razorpay_order_id: Optional[str] = None
    razorpay_key_id: Optional[str] = None
    amount_paise: int
    currency: str = "INR"
    is_test_mode: bool
    payment_method: str = "online"
    subtotal: float
    coupon_code: Optional[str] = None
    discount_amount: float = 0.0
    delivery_fee: float = 0.0
    tax_amount: float = 0.0
    total: float = 0.0
    slot_start: Optional[datetime] = None
    slot_end: Optional[datetime] = None


class VerifyPaymentRequest(BaseModel):
    order_id: str
    razorpay_payment_id: Optional[str] = None
    razorpay_order_id: Optional[str] = None
    razorpay_signature: Optional[str] = None
