"""
Barcode/QR package scanning (Phase 8).

No new "package" concept was introduced — this project's delivery
model is already one DeliveryRecordDB per package (there's no
multi-parcel-per-order granularity anywhere else in the app), so a
delivery's own `id` IS the package code. Scanning that ID (via a QR
code encoding it, generated by GET /deliveries/{id}/package-qr) is
what "scanning a package" means here; there's no separate barcode
value to keep in sync with the delivery record.

PackageScanDB is a pure ADDITIVE tracking/audit layer on top of the
existing delivery status flow — scanning a stage does NOT itself
change delivery.status (the agent still does that via the normal PATCH
endpoint, exactly as before). This is deliberate: conflating "I scanned
this package at the hub" with "this delivery's status is now X" would
mean scanning-related code reaching into and modifying core delivery
lifecycle logic, which is exactly the kind of scope creep the project
brief warns against. Scanning tells you WHERE a package has physically
been; delivery.status tells you what stage the order is at — related,
but kept as two separate facts.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import Column, String, DateTime, Boolean, Enum as SqlEnum
from pydantic import BaseModel
from typing import Optional

from app.db.session import Base


class ScanType(str, enum.Enum):
    pickup = "pickup"
    hub = "hub"
    out_for_delivery = "out_for_delivery"
    delivery = "delivery"
    return_ = "return"


class PackageScanDB(Base):
    __tablename__ = "package_scans"

    id = Column(String, primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    org_id = Column(String, index=True, nullable=False)
    delivery_id = Column(String, index=True, nullable=False)  # the scanned code IS the delivery id — see module docstring

    scan_type = Column(SqlEnum(ScanType), nullable=False)
    scanned_by_user_id = Column(String, nullable=True)
    location_note = Column(String, nullable=True)  # e.g. "Hub 3" or free-text where the scan happened

    scanned_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    # True when this scan was captured while the agent's device was
    # offline and only reached the server later via a queued retry —
    # same pattern/reasoning as ProofOfDeliveryDB.captured_offline
    # (Phase 1). Informational only.
    captured_offline = Column(Boolean, nullable=False, default=False)


# ---------- Pydantic Schemas ----------

class ScanIn(BaseModel):
    scan_type: ScanType
    location_note: Optional[str] = None
    scanned_at: Optional[datetime] = None
    captured_offline: bool = False


class ScanOut(BaseModel):
    id: str
    delivery_id: str
    scan_type: ScanType
    scanned_by_user_id: Optional[str] = None
    location_note: Optional[str] = None
    scanned_at: datetime
    captured_offline: bool

    class Config:
        from_attributes = True


class ScannedPackageOut(BaseModel):
    """What GET /scan/{code} resolves a scanned code to — just enough for the scanning UI to show 'you scanned order X, currently status Y' before recording the actual scan."""
    delivery_id: str
    order_id: str
    status: str
    agent_id: Optional[str] = None

    class Config:
        from_attributes = True
